export const actions = {
  products: {
    DATA_FETCHING: "PRODUCT_DATA_FETCHING",
    DATA_FETCHED: "PRODUCT_DATA_FETCHED",
    DATA_CREATE: "PRODUCT_DATA_CREATE",
    DATA_FETCH_ERROR: "PRODUCT_DATA_FETCH_ERROR",
    DATA_DELETE: "PRODUCT_DATA_DELETE",
    USER_DATA_EDIT: "PRODUCT_USER_DATA_EDIT",
    IMAGE_UPDATED: "PRODUCT_IMAGE_UPDATED",
  },
};
